
export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_COMMENT_STATE_CHANGE = 'USER_COMMENT_STATE_CHANGEF'
export const USER_OPTION_STATE_CHANGE = 'USER_OPTION_STATE_CHANGE'
export const USER_REPORTEDDISCUSSION_STATE_CHANGE = 'USER_REPORTEDDISCUSSION_STATE_CHANGE'
export const DISCUSSION_ROOM_STATE_CHANGE = 'DISCUSSION_ROOM_STATE_CHANGE'
export const USER_REQUESTFORAMENTOR_STATE_CHANGE ='USER_REQUESTFORAMENTOR_STATE_CHANGE'
export const USER_REQUESTTOBEAMENTOR_STATE_CHANGE ='USER_REQUESTTOBEAMENTOR_STATE_CHANGE'

//USER_REPORTEDdISCUSSION_STATE_CHANGE
// export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
// export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'

// export const CLEAR_DATA = 'CLEAR_DATA'
